#!/usr/bin/env bash
set -euo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║  Maritime Compliance Platform — Installer    ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo

# ─── Check prerequisites ─────────────────────────────────────────────────────

check_command() {
  if ! command -v "$1" &>/dev/null; then
    echo -e "${RED}ERROR: $1 is required but not installed.${NC}"
    echo "  Install it and re-run this script."
    exit 1
  fi
}

check_command docker
check_command "docker compose" || check_command docker-compose

# Verify Docker is running
if ! docker info &>/dev/null; then
  echo -e "${RED}ERROR: Docker daemon is not running. Start Docker and try again.${NC}"
  exit 1
fi

echo -e "${GREEN}✓ Prerequisites met${NC}"
echo

# ─── Vessel setup wizard ─────────────────────────────────────────────────────

echo -e "${BOLD}Vessel Setup${NC}"
echo "Enter vessel information (press Enter to skip optional fields):"
echo

read -rp "  Vessel name: " VESSEL_NAME
while [[ -z "$VESSEL_NAME" ]]; do
  echo -e "  ${YELLOW}Vessel name is required.${NC}"
  read -rp "  Vessel name: " VESSEL_NAME
done

read -rp "  IMO number (optional): " VESSEL_IMO

echo "  Vessel types: small_passenger, passenger, cargo, tanker, towing, offshore_supply, fishing, other"
read -rp "  Vessel type [small_passenger]: " VESSEL_TYPE
VESSEL_TYPE=${VESSEL_TYPE:-small_passenger}

read -rp "  Flag state (ISO code) [US]: " FLAG_STATE
FLAG_STATE=${FLAG_STATE:-US}

read -rp "  Gross tonnage (optional): " GROSS_TONNAGE

echo

# ─── Create .env file ────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env"

cat > "$ENV_FILE" <<EOF
# Generated by install.sh — $(date -Iseconds)
DATABASE_URL=postgresql://maritime:maritime@localhost:5432/maritime
POSTGRES_USER=maritime
POSTGRES_PASSWORD=maritime
POSTGRES_DB=maritime
REDIS_URL=redis://localhost:6379
OLLAMA_URL=http://localhost:11434
PORT=3000
NODE_ENV=production
LOG_LEVEL=info
VESSEL_NAME=${VESSEL_NAME}
VESSEL_IMO=${VESSEL_IMO}
VESSEL_TYPE=${VESSEL_TYPE}
FLAG_STATE=${FLAG_STATE}
GROSS_TONNAGE=${GROSS_TONNAGE}
EOF

echo -e "${GREEN}✓ Configuration saved${NC}"

# ─── Pull images and start services ──────────────────────────────────────────

echo
echo -e "${BOLD}Starting services...${NC}"
cd "$SCRIPT_DIR"
docker compose pull
docker compose up -d

# Wait for postgres to be healthy
echo -n "Waiting for database"
for i in $(seq 1 30); do
  if docker compose exec -T postgres pg_isready -U maritime &>/dev/null; then
    break
  fi
  echo -n "."
  sleep 2
done
echo -e " ${GREEN}ready${NC}"

# ─── Run migrations ──────────────────────────────────────────────────────────

echo -e "${BOLD}Running database migrations...${NC}"
docker compose exec -T vessel-agent node -e "
  import('file:///app/packages/db/src/migrate.ts')
" 2>/dev/null || {
  # Fallback: run migrations from host if container approach fails
  echo "Running migrations from host..."
  cd "$SCRIPT_DIR/.."
  DATABASE_URL="postgresql://maritime:maritime@localhost:5432/maritime" pnpm --filter @maritime/db migrate
}

echo -e "${GREEN}✓ Migrations complete${NC}"

# ─── Seed vessel ──────────────────────────────────────────────────────────────

echo -e "${BOLD}Creating vessel record...${NC}"
docker compose exec -T postgres psql -U maritime -d maritime -c "
  INSERT INTO vessels (name, imo_number, vessel_type, flag_state, gross_tonnage, compliance_status)
  VALUES (
    '${VESSEL_NAME}',
    NULLIF('${VESSEL_IMO}', ''),
    '${VESSEL_TYPE}',
    '${FLAG_STATE}',
    NULLIF('${GROSS_TONNAGE}', '')::numeric,
    'unknown'
  )
  ON CONFLICT DO NOTHING;
"
echo -e "${GREEN}✓ Vessel created${NC}"

# ─── Done ─────────────────────────────────────────────────────────────────────

echo
echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║  Installation complete!                      ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo
echo -e "  Dashboard available at ${GREEN}http://localhost:3000${NC}"
echo -e "  PostgreSQL at localhost:5432"
echo -e "  Redis at localhost:6379"
echo -e "  Ollama at localhost:11434"
echo
echo -e "  Vessel: ${BOLD}${VESSEL_NAME}${NC}"
echo
